<?php
/*
	opentime
	$Author: perrick $
	$URL: svn://svn.noparking.net/var/repos/opentime/cfg/param.inc.php.dist $
	$Revision: 5943 $

	Copyright (C) No Parking 2012 - 2013
*/

## définition des extensions
$param['ext_time'] = "1";		// activation de la gestion du temps (1 - oui, par défaut)
$param['ext_activities'] = "1";		// activation de la gestion des activités (1 - oui, par défaut)
$param['ext_followup'] = "1";		// activation du suivi (1 - oui, par défaut)
$param['ext_absences'] = "1";		// activation des absences (1 - oui, par défaut)
$param['ext_holidays'] = "1";		// activation des demandes de congés (0 - non, par défaut)
$param['ext_absencecredit'] = "0";		// activation du compte épargne temps (0 - non, par défaut)
$param['ext_payrollelements'] = "0";		// activation des éléments de paye (0 - non, par défaut)
$param['ext_expenses'] = "1";		// activation des notes de frais (0 - non, par défaut)
$param['ext_requests'] = "0";		// activation des requêtes (0 - non, par défaut)
$param['ext_contacts'] = "0";		// activation des contacts (0 - non, par défaut)
$param['ext_planning'] = "0";		// activation du planning (0 - non, par défaut)
$param['ext_calendar'] = "0";		// activation du calendrier (0 - non, par défaut)
$param['ext_events'] = "0";		// activation des évènements sur le calendrier (0 - non, par défaut)
$param['ext_finances'] = "1";		// activation des finances (1 - oui, par défaut)
$param['ext_quotes'] = "0";		// activation des devis (0 - non, par défaut)
$param['ext_analytical'] = "0";		// activation de la compta analytique (0 - non, par défaut)
$param['ext_timekeeper'] = "0";		// activation de la pointeuse (0 - non, par défaut)
$param['ext_timeannual'] = "0";		// activation de la gestion annualisée du temps (0 - non, par défaut)
$param['ext_recuperation'] = "0";		// activation de la récupération du temps (0 - non, par défaut)
$param['ext_invoices'] = "0";		// activation de la création des factures (0 - non, par défaut)
$param['ext_userfeedback'] = "1";		// activation du feed-back pour un utilisateur (1 - oui, par défaut)
$param['ext_userproject'] = "0";		// activation des projets pour un utilisateur sans droit (0 - non, par défaut)
$param['ext_todo'] = "1";		// activation de l'aide via les to-dos internes (1 - oui, par défaut)
$param['ext_chargeplan'] = "0";		// activation du plan de charges (0 - non, par défaut)
$param['ext_taxrefund'] = "0";		// activation du Crédit Impôt Recherche (0 - non, par défaut)
$param['ext_currencies'] = "1";		// activation de la gestion multi-devises (0 - non, par défaut)

## définition des niveaux d'activité
$param['level_0'] = "client";		// intitulé du niveau supérieur de l'activité (client, par défaut)
$param['levels_0'] = "clients";		// intitulé des niveaux supérieurs de l'activité (clients, par défaut)
$param['newlevel_0'] = "nouveau client";		// intitulé d'un nouveau niveau supérieur de l'activité (nouveau client, par défaut)
$param['level_0_link'] = "lien client";		// intitulé d'un paramètre complémentaire sur les niveaux supérieurs de l'activité (lien client, par défaut)
$param['level_1'] = "projet";		// intitulé du niveau intermédiaire de l'activité (projet, par défaut)
$param['levels_1'] = "projets";		// intitulé des niveaux intermédiaires de l'activité (projets, par défaut)
$param['newlevel_1'] = "nouveau projet";		// intitulé d'un nouveau niveau intermédiaire de l'activité (nouveau projet, par défaut)
$param['level_2'] = "sous-projet";		// intitulé du niveau inférieur de l'activité (sous-projet, par défaut)
$param['levels_2'] = "sous-projets";		// intitulé des niveaux supérieurs de l'activité (sous-projets, par défaut)
$param['level_1_link'] = "lien projet";		// intitulé d'un paramètre complémentaire sur les niveaux inférieurs de l'activité (lien projet, par défaut)
$param['order_level_1'] = "ASC";		// trier les dossiers dans les menus (ASC - ascendant, par défaut)
$param['show_level_2'] = "1";		// autoriser la création de dossiers de niveau inférieur (0 - non, par défaut)
$param['level_0_handling'] = "1";		// utilisation de l'application pour la gestion du niveau supérieur de l'activité (1 - oui, par défaut)
$param['level_1_handling'] = "1";		// utilisation de l'application pour la gestion du niveau intermédiaire de l'activité (1 - oui, par défaut)
$param['customeroptions_number'] = "0";		// affichage du code analytique d'un customer (1 - oui, par défaut)
$param['customeroptions_billable'] = "0";		// affichage de l'option d'une activité facturable (0 - non, par défaut)
$param['customeroptions_parentproject'] = "1";		// affichage de l'option des noms des projets parents par activité (0 - non, par défaut)
$param['customeroptions_color'] = "0";		// affichage de l'option d'une couleur par activité (0 - non, par défaut)
$param['customeroptions_textareas'] = "";	// liste des champs possibles -- avec du texte libre -- pour les customers ("", par défaut)
$param['customeroptions_text'] = "";		// liste des champs possibles -- avec du texte libre -- pour les customers ("", par défaut)
$param['customeroptions_textunique'] = ""; // liste des champs possibles -- avec du texte libre mais unique -- pour les customers ("", par défaut)
$param['customeroptions_date'] = "";		// liste des champs possibles -- avec une date -- pour les customers ("", par défaut)
$param['customeroptions_user'] = "";		// liste des champs possibles -- avec un utilisateur -- pour les customers ("", par défaut)
$param['customeroptions_selects'] = ""; // liste des champs possibles -- avec des select -- pour les customers ("", par défaut)
$param['customeroptions_selectsmulti'] = ""; // liste des champs possibles -- avec des select -- pour les customers ("", par défaut)
$param['customeroptions_file'] = "";		// liste des champs possibles -- avec un input de type file -- pour les clients ("", par défaut)
$param['projectoptions_number'] = "0";		// affichage du code analytique d'un project (1 - oui, par défaut)
$param['projectoptions_color'] = "0";		// affichage de l'option d'une couleur par projet (0 - non, par défaut)
$param['projectoptions_billable'] = "0";		// affichage de l'option d'un projet facturable (0 - non, par défaut)
$param['projectoptions_responsible'] = "0";		// affichage de l'option du responsable d'un projet (0 - non, par défaut)
$param['projectoptions_external'] = "0";		// affichage de l'option du code extérieur d'un projet (0 - non, par défaut)
$param['projectoptions_success'] = "0";		// affichage de l'option de réussite d'un projet (0 - non, par défaut)
$param['projectoptions_clientsatisfaction'] = "0";		// affichage de l'option de la satisfaction d'un client sur un projet (0 - non, par défaut)
$param['projectoptions_difficulty'] = "0";		// affichage de l'option de difficulté d'un projet (0 - non, par défaut)
$param['projectoptions_priority'] = "0";		// affichage de l'option de priorité d'un projet (0 - non, par défaut)
$param['projectoptions_ordernumber'] = "0";		// affichage de l'option du numéro de commande d'un projet (0 - non, par défaut)
$param['projectoptions_orderdescription'] = "0";		// affichage de l'option de la description de commande d'un projet (0 - non, par défaut)
$param['projectoptions_taxrefunded'] = "0";		// affichage de l'option de la description pour le CIR d'un projet (0 - non, par défaut)
$param['projectoptions_currency'] = "0";		// affichage de l'option de la devise d'un projet (0 - non, par défaut)
$param['projectoptions_textareas'] = ""; // liste des champs possibles -- avec du texte libre -- pour les projects ("", par défaut)
$param['projectoptions_text'] = ""; // liste des champs possibles -- avec du texte libre -- pour les projects ("", par défaut)
$param['projectoptions_date'] = ""; // liste des champs possibles -- avec une date -- pour les projects ("", par défaut)
$param['projectoptions_user'] = ""; // liste des champs possibles -- avec un utilisateur -- pour les projects ("", par défaut)
$param['projectoptions_selects'] = ""; // liste des champs possibles -- avec un select -- pour les projects ("", par défaut)
$param['projectoptions_selectsmulti'] = ""; // liste des champs possibles -- avec un select -- pour les projects ("", par défaut)
$param['projectoptions_file'] = "";		// liste des champs possibles -- avec un input de type file -- pour les projects ("", par défaut)
$param['level_projectstatus'] = "3";			// niveau de visibilité des projets

## définition des niveaux d'utilisateur
$param['user_aa'] = "dirigeant";		// intitulé du super-administrateur de l'application (dirigeant, par défaut)
$param['user_a'] = "chef de projet";		// intitulé de l'administrateur de l'application (chef de projet, par défaut)
$param['user_b'] = "responsable administratif";		// intitulé du responsable administratif (responsable administratif, par défaut)
$param['user'] = "utilisateur";		// intitulé de l'utilisateur de l'application (utilisateur, par défaut)
$param['users'] = "utilisateurs";		// intitulé des utilisateurs de l'application (utilisateurs, par défaut)
$param['user_link'] = "lien utilisateur";		// intitulé d'un paramètre complémentaire sur les utilisateurs de l'application (lien utilisateur, par défaut)
$param['user_block_ip'] = "1";		// test de blocage de l'adresse IP de l'utilisateur (1 - oui, par défaut)
$param['user_new_a'] = "1";		// création de nouveaux utilisateurs par un chef de projet (1 - oui, par défaut)
$param['user_new_b'] = "1";		// création de nouveaux utilisateurs par un responsable administratif (0 - non, par défaut)
$param['user_handling'] = "1";		// utilisation de l'application pour la gestion des utilisateurs (1 - oui, par défaut)
$param['user_preferences'] = "1"; // utilisation de l'application pour la gestion des préférences des utilisateurs (1 - oui, par défaut)
$param['user_passwordhandling'] = "1";		// utilisation de l'application pour la gestion des mots de passe des utilisateurs (1 - oui, par défaut)
$param['user_logincontent'] = "login.php";		// nom de la page à utiliser pour gérer le formulaire de login pour l'application (login.php, par défaut)
$param['user_update'] = "300";		// durée d'attente entre deux vérifications pour l'update de la table des utilisateurs (300 - 5 minutes, par défaut)
$param['user_menu'] = "name"; // affichage de l'utilisateur dans la liste déroulante de navigation (name - nom complet [name], par défaut)
$param['user_security'] = "0";		// sécurité accrue sur l'affectation et la visibilité des projets au niveau des utilisateurs (0 - non, par défaut)
$param['user_weekdetails'] = "0";		// archivage ou non des semaines types (0 - non, par défaut)
$param['useroptions_birth'] = "0";		// affichage de la date de naissance dans les préférences utilisateurs (0 - non, par défaut)
$param['useroptions_bankholidays'] = "0";		// affichage de l'option du pays pour les jours fériés (0 - non, par défaut)
$param['useroptions_holidaysdelegation'] = "0";		// affichage de l'option d'une délégation de signature pour les congés (0 - non, par défaut)
$param['useroptions_company'] = "0";		// affichage de l'option de l'entreprise (0 - non, par défaut)
$param['useroptions_direction'] = "0";		// affichage de l'option de la direction d'un salarié (0 - non, par défaut)
$param['useroptions_service'] = "0";		// affichage de l'option du service d'un salarié (0 - non, par défaut)
$param['useroptions_department'] = "0";		// affichage de l'option du département d'un salarié (0 - non, par défaut)
$param['useroptions_contracttime'] = "0";		// affichage de l'option du temps par mois prévu dans le contrat (0 - non, par défaut)
$param['useroptions_validationcondition'] = "0";		// affichage de l'option des conditions de validation individualisée (0 - non, par défaut)
$param['useroptions_askedvalidationcondition'] = "0";		// affichage de l'option des conditions de demande de validation individualisée (0 - non, par défaut)
$param['useroptions_chargeplanvalidation'] = "0";		// validation des plans de charge (0 - non, par défaut)
$param['usercompany_list'] = "";		// liste des entreprises possibles dans les préférences d'un salarié ("", par défaut)
$param['useroptions_projectdefault'] = "0";		// affichage de l'option permettant à chaque utilisateur de définir un projet par défaut (0 - non, par défaut)
$param['useroptions_task_id'] = "1";		// affichage du métier dans les préférences utilisateurs (1 - oui, par défaut)
$param['useroptions_task'] = "0";		// affichage de l'option permettant à chaque utilisateur de définir ses métiers (0 - non, par défaut)
$param['useroptions_hierarchicalresponsible'] = "0";		// affichage de l'option d'un responsable hiérarchique à chaque utilisateur (0 - non, par défaut)
$param['useroptions_position'] = "0";		// affichage de l'option de statut -- cadre / non-cadre -- des utilisateurs (0 - non, par défaut)
$param['useroptions_entrydate'] = "0";		// affichage de l'option de la date d'arrivée dans la société (0 - non, par défaut)
$param['useroptions_sex'] = "0";		// affichage de l'option du sexe de l'utilisateur (0 - non, par défaut)
$param['useroptions_userhours'] = "1";		// affichage de l'option du type de saisie du temps de l'utilisateur (0 - non, par défaut)
$param['useroptions_timeunit'] = "0";		// affichage de l'option de l'unité pour la saisie du temps de l'utilisateur (0 - non, par défaut)
$param['useroptions_localelang'] = "0";		// affichage de l'option de la langue par défaut pour l'utilisateur (0 - non, par défaut)
$param['useroptions_creditcard_number'] = "0";		// affichage de l'option du numéro de carte de crédit pour les utilisateurs (0 - non, par défaut)
$param['useroptions_requestprofile'] = "0";		// affichage de l'option du profil pour les mémos (0 - non, par défaut)
$param['useroptions_requestprofile_profiles'] = ""; // liste des profils possibles les mémos ("", par défaut)
$param['useroptions_weekend'] = "1";				// affichage de l'option de permettant de remplir les cases d'un jour de weekend (0 - non, par défaut)
$param['useroptions_cv'] = "0";		// affichage de l'option du chargement d'un CV (0 - non, par défaut)
$param['useroptions_diploma'] = "0";		// affichage de l'option du chargement d'un diplôme (0 - non, par défaut)
$param['useroptions_jobtitle'] = "0";		// affichage de l'option du titre d'un utilisateur (0 - non, par défaut)
$param['useroptions_color'] = "0";		// affichage d'une couleur dans les préférences utilisateurs (0 - non, par défaut)
$param['useroptions_hourlink'] = "0";		// affichage des liens heures dans les préférences utilisateurs (0 - non, par défaut)
$param['useroptions_checkboxes'] = "";		// liste des cases à chocher possibles pour les utilsateurs ("", par défaut)

# définition des permissions
$param['permissions_adduser'] = "a";		// permission de créer une nouvel utilisateur (a - user_a, par défaut) 
$param['permissions_edituseraffectation'] = "";		// permission de modifier l'affectation d'un utilisateur ("" - user, par défaut) 
$param['permissions_edituserpreferences'] = "a";		// permission de modifier les préférences d'un utilisateur (a - user_a, par défaut)
$param['permissions_pickaffectationfromallcustomer'] = "aa";		// permission de choisir l'affectation parmi tous les clients ("aa" - user_aa, par défaut)
$param['permissions_pickaffectationfromwowncustomer'] = "a";		// permission de choisir l'affectation parmi les clients déjà affectés ("a" - user_a, par défaut)
$param['permissions_pickaffectationfromwownproject'] = "";		// permission de choisir l'affectation parmi les clients déjà affectés ("" - user, par défaut)
$param['permissions_editcustomer'] = "aa";		// permission d'éditer un client ("aa" - user_aa, par défaut)
$param['permissions_editproject'] = "a";		// permission d'éditer un projet ("a" - user_a, par défaut)
$param['permissions_validatetime'] = "";		// permission de valider la saisie des temps d'un utilisateur ("" - user, par défaut)
$param['permissions_validatetimewithrecuperation'] = "aa";		// permission de valider la saisie des temps d'un utilisateur avec récupération ("aa" - user_aa, par défaut)
$param['permissions_forcetimekeeperwritable'] = "a";		// permission de forcer la saisie d'une pointeuse ("a" - user_a, par défaut)

# définition des options de la pointeuse
$param['timekeeper_writable'] = "0";		// utilisation d'une pointeuse ouverte en écriture (0 - non, par défaut)
$param['timekeeper_starter'] = "1";		// utilisation d'un starter -- pour la pointeuse ouvert uniquement (1 - oui, par défaut)
$param['timekeeper_break'] = "0";		// utilisation d'une pause obligatoire dans les saisies (0 - non, par défaut)
$param['timekeeper_breakspan'] = "1800";		// durée de la pause obligatoire (1800 - 30 minutes, par défaut)
$param['timekeeper_breakday'] = "25200";		// durée de travail consécutif avant le déclenchement de la pause obligatoire (25200 - 7 heures, par défaut)
$param['timekeeper_rounding'] = "0";		// arrondi des heures de la pointeuse (0 - aucun, par défault)
$param['timekeeper_closeauto'] = "0";		// fermer la pointeuse automatiquement après ce nombre d'heures (0 - ne pas la fermer, par défault)
$param['timekeeper_closeat'] = "0";		// fermer la pointeuse automatiquement à cette heure (0 - ne pas la fermer, par défault)
$param['useroptions_timekeeper'] = "0";		// affichage de l'option du choix individuelle pour la pointeuse (0 - non, par défaut)
$param['useroptions_timekeeperdefault'] = "0";		// affichage de l'option d'une saisie de pointeuse automatique (0 - non, par défaut)
$param['timekeeper_modifiabledefault'] = "0"; 		// permet à l'utilisateur de définir sa propre pointeuse automatique (0 - non, par défaut)
$param['timekeeper_fillhours'] = "0"; 		// permet à l'utilisateur de compléter sa semaine en fonction de sa pointeuse (0 - non, par défaut)

## définition des métiers utilisateur
$param['task'] = "métier";		// intitulé du métier (métier, par défaut)
$param['tasks'] = "métiers";		// intitulé des métiers (métiers, par défaut)

## définition des types de coûts
$param['projectestimate_multiple'] = "0"; // ajustement des estimations par projet (0 - non, par défaut)
$param['projectestimate_restrictedtousers'] = "0"; // restreindre les métiers d'un prévisionnel aux utilisateurs (0 - non, par défaut)
$param['sales'] = "factures client";		// intitulé de la facture client (factures client, par défaut)
$param['purchases'] = "factures fournisseur";		// intitulé de la facture fournisseur (factures fournisseur, par défaut)
$param['analyticalcode'] = "code analytique";		// intitulé du code analytique (code analytique, par défaut)
$param['salefigure'] = "chiffre d'affaires";		// intitulé du chiffre d'affaires (chiffre d'affaires, par défaut)
$param['salefigureoptions_maturity'] = "0";		// affichage de l'option de l'échéance d'une facture (0 - non, par défaut)
$param['salefigureoptions_maturitydate'] = "0";		// affichage de l'option de la date de l'échéance d'une facture (0 - non, par défaut)
$param['salefigureoptions_status'] = "0";		// affichage de l'option du statut d'une facture (0 - non, par défaut)
$param['salefigureoptions_paymentdate'] = "0";		// affichage de l'option de la date de règlement d'une facture (0 - non, par défaut)
$param['salefigureoptions_paymentmode'] = "0";		// affichage de l'option du mode de règlement d'une facture (0 - non, par défaut)
$param['salefigureoptions_paymentcomment'] = "0";		// affichage de l'option du commentaire de règlement d'une facture (0 - non, par défaut)
$param['cost_direct'] = "direct";		// intitulé du coût interne plancher (direct, par défaut)
$param['cost_production'] = "production";		// intitulé du coût de revient (production, par défaut)
$param['cost_anticipation'] = "1";		// calcul du coût avec les heures à venir (1 - oui, par défaut)
$param['cost_rateproject'] = "1";		// calcul du coût avec les taux par projet (0 - non, par défaut)

## définition des paramètres fiscaux
$param['purchase_rate'] = "0";		// taux sur le chiffre d'affaires prévisionnel pour les charges directs (0 - 0%, par défaut)
$param['fiscal_month'] = "1";		// mois du début de l'année fiscale (1 - janvier, par défaut)
$param['holiday_month'] = "1";		// mois du début de l'année pour les congés (1 - janvier, par défaut)
$param['currency'] = "&euro;";		// intitulé de la monnaie utilisée (&euro; - &euro;, par défaut)
$param['vat_rate'] = "19.6";		// taux de TVA standard (19.6 - 19.6%, par défaut)

## définition des locales internes
$param['locale_timezone'] = "Europe/Paris";		// locale pour le fuseau horaire (Europe/Paris, par défaut)
$param['locale_lang'] = "fr_FR";		// locale pour la langue (fr_FR, par défaut)

## définition des paramètres de la gestion du temps
$param['serialized_week'] = "a:7:{i:0;i:25200;i:1;i:25200;i:2;i:25200;i:3;i:25200;i:4;i:25200;i:5;i:0;i:6;i:0;}";		// semaine type pour un salarié (a:5:{i:0;i:25200; i:1;i:25200; i:2;i:25200; i:3;i:25200; i:4;i:25200;i:5;i:0;i:6;i:0;} - 8h 8h 8h 8h 7h 0h 0h, par défaut)
$param['hour_link'] = "";		// intitulé d'un paramètre complémentaire sur les heures (lien heure, par défaut)
$param['file_userprocess'] = "";		// premier onglet du menu "process" des utilisateurs ("", par défaut)
$param['file_userhours'] = "userhoursline.php";		// fichier PHP pour la saisie des heures sur un utilisateur (userhoursmenu.php, par défaut)
$param['file_projecthours'] = "projecthours.php";		// fichier PHP pour la saisie des heures sur un projet (projecthours.php, par défaut)
$param['file_userplanning'] = "userplanningrequests.php";		// fichier PHP pour la gestion du planning d'un utilisateur (userplanningrequests.php, par défaut)
$param['file_projectplanning'] = "projectplanningrequests.php";		// fichier PHP pour la gestion du planning d'un projet (projectplanningrequests.php, par défaut)
$param['file_adminplanning'] = "followupplanningrequests.php";		// fichier PHP pour le planning administratif (followupplanningrequests.php, par défaut)
$param['file_defaultcontent'] = "";		// fichier PHP pour l'affichage par défaut lors du démarrage (userhoursmenu.php, par défaut)
$param['validation_condition'] = "=";		// condition de validation d'une semaine : <, <=, =, >= ou > (=, par défaut)
$param['askedvalidation_condition'] = "=";		// condition de de demande de validation d'une semaine : <, <=, =, >= ou > (=, par défaut)
$param['validation_lock'] = "0"; //clôturer définitivement les validations de temps (0 - non, par défaut)
$param['validation_troubles'] = "0";		// affichage des problèmes sur la validation des temps (0 - non, par défaut)
$param['validation_anticipate'] = "1";		// validation par anticipation pour les utilisateurs (1 - oui, par défaut)
$param['validation_project'] = "0";		// validation complémentaire pour les projets (0 - non, par défaut)
$param['color_condition_0'] = "7";		// nb de jours pour le changement de couleurs 'alerte orange' (7, par défaut)
$param['color_condition'] = "14";		// nb de jours pour le changement de couleurs 'alerte rouge' (14, par défaut)
$param['hours_parent'] = "1";		// remplir les cases d'un parent (1 - oui, par défaut)
$param['hours_weekend'] = "0";		// remplir les cases d'un jour de weekend (0 - non, par défaut)
$param['hours_taskid'] = "1";		// utiliser les métiers pour la saisie du temps (0 - non, par défaut)
$param['hours_comment'] = "1";		// utiliser les commentaires pour la saisie du temps (1 - oui, par défaut)
$param['color_condition_0'] = "7";		// nb de jours pour le changement de couleurs 'alerte orange' (7, par défaut)
$param['hours_taskestimated'] = "0";		// utiliser uniquement les métiers avec une estimation pour la saisie du temps (0 - non, par défaut)
$param['hours_recurrent'] = "0";		// utiliser la récurrence (0 - non, par défaut)
$param['planning_strict'] = "0";		// saisie bloqué pour le planning d'un projet calé (0 - non, par défaut)
$param['absence_quarterday'] = "7200";		// durée du quart de journée standard (7200 - 2h, par défaut)
$param['absence_halfday'] = "14400";		// durée de la demi-journée standard (14400 - 4h, par défaut)
$param['absence_fullday'] = "25200";		// durée de la journée standard (25200 - 7h, par défaut)
$param['absence_fractionmode'] = "fixed";		// mode de calcul pour les fractions de journées (fixed - durée fixe, par défaut)
$param['absence_daymode'] = "weekdetails";	// mode de calcul de la durée d'une journée d'absence (weekdetails - calcul à partir de la journée type, par défaut)
$param['paidholidaysweeks_no'] = "5";		// nb de semaines de congés payés par an (5, par défaut)
$param['project_prefill'] = "";		// nb de semaines pour le pré-remplissage des dossiers sur la grille des temps (0, par défaut)
$param['parent_project'] = "";		// noms des sous-projets à ajouter automatiquement ("", par défaut)
$param['timekeeper_user'] = "0";		// choix par utilisateur de l'utilisation de la pointeuse (0 - non, par défaut)
$param['chargeplan_update'] = "";		// date de la dernière validation du plan de charge ("", par défaut)
$param['chargeplan_period'] = "d";		// période sur laquelle afficher le plan de charge ("m" - mois, par défaut)
$param['time_unit'] = "d";		// unité d'affichage des temps : h-heure ou d-jour (h - heure, par défaut)
$param['time_unit_round'] = "2";		// nombre de décimales à afficher pour les arrondis de journée (2, par défaut)
$param['chargeplan_validation'] = "0";		// validation des plans de charge (0 - non, par défaut)
$param['payrollelements_mode'] = "month";		// période de calcul pour les éléments de paye (month - mensuel, par défaut)
$param['payrollelements_bankholidays'] = "0";		// ajout des jours fériés dans les exports des éléments de paye (0 - non, par défaut)

## définition des paramètres de l'annualisation du temps de travail
$param['annualtime_month'] = "1";		// mois du début de l'année pour l'annualisation du temps de travail (1 - janvier, par défaut)
$param['annualtime_week'] = "1";		// semaine du début de l'année pour l'annualisation du temps de travail (1 - première semaine de janvier, par défaut)
$param['annualtime_switch'] = "0";		// reprise automatique d'une année sur l'autre des temps de travail annualisés (0 - non, par défaut)
$param['annualtime_maxtimeswitch'] = "";		// durée maximum du temps repris d'une année sur l'autre, en secondes (28800, par défaut)
$param['annualtime_mintimeswitch'] = "";		// durée minimum du temps repris d'une année sur l'autre, en secondes (-28800, par défaut)
$param['useroptions_annualaddition'] = "0";		// affichage de l'option du choix de la méthode pour le cumul annuel (0 - non, par défaut)

## définition des paramètres de la gestion des absences
$param['hours_holidays'] = "0";		// remplir les cases d'un jour de congés pris (0 - non, par défaut)
$param['level_holidays'] = "6";		// niveau de blocage pour la saisie des congés individuelles (6 - récupération, par défaut)
$param['level_holidayrequest'] = "3";		// niveau de blocage pour la saisie des demandes de congés individuelles (3 - RTT, par défaut)
$param['validation_holidays'] = "1";		// validation possible par un responsable hiérarchique de niveau 'a' (1 - oui, par défaut)
$param['calendar_holidays'] = "";		// liste des calendriers utilisés pour la gestion des jours fériés ("", par défaut)
$param['input_holidayhalf'] = "1";		// affichage des demi-journées dans les demandes de congés (1 - oui, par défaut)
$param['input_holidayquarter'] = "0";		// affichage des quart de journées dans les demandes de congés (0 - non, par défaut)
$param['input_holidayspan'] = "0";		// affichage du temps précis dans les demandes de congés (0 - non, par défaut)
$param['balance_holidays'] = "halfday";		// mode de calcul pour le décompte des absences et de leurs compteurs (halfday - arrondi par demi-journée et journée, par défaut)
$param['substraction_holidays'] = "pro-rata";		// mode de calcul pour les comptes d'absences des salariés à temps partiel (pro-rata - au pro-rata de leur semaine type, par défaut)
$param['holidays_export'] = "without-balance";		// format de l'exportation des congés au format Excel (without-balance - sans compteur, par défaut)
$param['holidays_automatic'] = "current";	// calcul du nombre d'heures prises en compte pour un jour férié (current - nombre d'heures du jour courant, par défaut)
$param['absence_payroll_elements'] = "0"; // affichage des éléments de paye (0 - non, par défaut)
$param['absence_usercompany_list'] = "";		// liste des entreprises dont les salariés sont affichés sur la synthèse des absences ("", par défaut)
$param['absence_requestcheck'] = "1";		// case cochée devant les demandes de congés (1 - oui, par défaut)
$param['absence_personal_exception'] = ""; // id absence personnel qui ne sont pas assimilable à des heures de travail ("", par défaut)
$param['absence_holidayrequest_lag'] = "0"; // décalage entre les dates de demande de congés et les jours effectifs (0 - non, par défaut)
$param['personalrequest_replace'] = "0";		// possibilité d'annuler et de remplacer une demade de congés (0 - non, par défaut)
$param['personalrequest_security'] = "0";		// sécurité accrue sur la confirmation d'une demande de congés (0 - affichée, par défaut)
$param['personalrequest_maxhalfdays'] = "0";		// possibilité de bloquer le nombre de demi-journées pour les demades de congés (0 - non, par défaut)
$param['personalrequest_alert'] = "0";		// envoi d'un message d'alerte à la confirmation d'une demande de congés (0 - non, par défaut)

## définition des paramètres de la gestion des projets et des requêtes
$param['request'] = "tâche";		// intitulé d'une requête (mémo, par défaut)
$param['requests'] = "tâches";		// intitulé des requêtes (mémos, par défaut)
$param['file_projectprocess'] = "projectdetails.php";		// premier onglet du menu "process" des projets (projectdetails.php, par défaut)
$param['request_detailed'] = "1";		// affichage des détails complets d'une requête (1 - oui, par défaut)
$param['request_weight'] = "0";		// affichage du poids d'une requête (0 - non, par défaut)
$param['request_weight_name'] = "poids";		// intitulé du poids d'une requête (poids, par défaut)
$param['request_weight_cursor'] = "0";		// affichage du curseur avec le poids réalisé et la vélocité mesurée (0 - non, par défaut)
$param['request_time'] = "0";		// saisie du temps du projet directement via la requête (0 - non, par défaut)
$param['request_autoassign'] = "1";		// affectation automatique du demandeur sur une nouvelle demande (0 - non, par défaut)
$param['request_archivedirection'] = "ASC";		// ordre de tri pour l'affichage de l'archive (ASC - ASC, par défaut)
$param['request_numberauto'] = "1"; // incrémentation automatique du champ numéro sur les demandes (1 - oui, par défaut)
$param['request_repetition'] = "0";		// possibilité de répéter automatiquement une requête (0 - non, par défaut)
$param['request_amount'] = "0";		// affichage du montant d'une requête (0 - non, par défaut)
$param['requestoptions_reference_autre_demande'] = "0"; // affichage de l'option 'référence à une autre demande' pour les mémos (0 - non, par défaut)
$param['requestoptions_selects'] = ""; // liste des champs possibles -- avec des select -- pour les mémos ("", par défaut)
$param['requestoptions_selectsmulti'] = ""; // liste des champs possibles -- avec des multiselect -- pour les mémos ("", par défaut)
$param['requestoptions_selectsuser'] = ""; // liste des champs possibles -- avec un utilisateur -- pour les mémos ("", par défaut)
$param['requestoptions_inputstext'] = ""; // liste des champs possibles -- avec du texte libre -- pour les mémos ("", par défaut)
$param['requestoptions_inputsdate'] = ""; // liste des champs possibles -- avec une date -- pour les mémos ("", par défaut)
$param['requestoptions_inputsnumber'] = ""; // liste des champs possibles -- avec un nombre -- pour les mémos ("", par défaut)
$param['requestoptions_inputsfile'] = ""; // liste des champs possibles -- avec pièce jointe -- pour les mémos ("", par défaut)
$param['requestoptions_textareas'] = ""; // liste des champs possibles -- avec une zone de texte -- pour les mémos ("", par défaut)

## définition des paramètres de la gestion des évènements
$param['event_type'] = "1";		// affichage du type d'évènement (1 - oui, par défaut)
$param['event_source'] = "0";		// affichage de la source de l'évènement (0 - non, par défaut)
$param['event_hourlink'] = "0";		// affichage du hourlink de l'évènement (0 - non, par défaut)

## définition des paramètres du tableau de bord
$param['nb_records'] = "50";		// nb d'enregistrements avant le passage à la feuille suivante (50, par défaut)
$param['nb_level_1'] = "20";		// nb de lettres affichés sur le titre des dossiers (20, par défaut)

## définition des paramètres du 'feed-back'
$param['feedback'] = "informations";		// nom pour l'onglet 'feedback' dans le menu "salarié" (retour, par défaut)
$param['userstatus_addition'] = "1";		// affichage du tableau des congés payés (1 - oui, par défaut)
$param['userstatus_holidays'] = "1";		// affichage du cumul des congés (1 - oui, par défaut)
$param['userstatus_reminder'] = "1";		// affichage de la date de dernière validation (1 - oui, par défaut)
$param['userstatus_piedouble'] = "1";		// affichage du graphique de répartition des projets (1 - oui, par défaut)
$param['userstatus_piedouble_1'] = "0";		// affichage du graphique de répartition des dossiers (0 - non, par défaut)
$param['userstatus_synthesis'] = "0";		// affichage de la synthèse sur une plage de date (0 - non, par défaut)
$param['userstatus_holidaysreport'] = "0";		// affichage du tableau des congés de l'équipe (0 - non, par défaut)

## définition des paramètres de la compta analytique
$param['analytical_projectdetails'] = "0";		// affichage d'une colonne avec les coûts salariaux sur le détail d'un projet (0 - non, par défaut)
$param['analytical_salarycoefficient'] = "1";		// coefficient de temps effectif à prendre en compte pour calculer le taux horaire salarial ("1", par défaut)

## définition des paramètres de la consultation des projets
$param['userproject_data'] = "1";		// affichage du tableau des données d'un projet (1 - oui, par défaut)
$param['userproject_customer'] = "0";		// affichage du tableau des données d'un client (0 - non, par défaut)
$param['userproject_hours'] = "1";		// affichage du tableau des heures d'un projet (1 - oui, par défaut)
$param['userproject_hourgraph'] = "1";		// affichage du graphique 'heures' d'un projet (1 - oui, par défaut)
$param['userproject_financialgraph'] = "1";		// affichage du graphique 'finances' d'un projet (1 - oui, par défaut)
$param['userproject_profitability'] = "0";		// affichage de la rentabilité d'un projet (0 - non, par défaut)
$param['userproject_hours_hourlink'] = "0";		// affichage du graphique 'heures par hourlink' d'un projet (0 - non, par défaut)
$param['userproject_useronly'] = "0";		// filtre des temps passés sur un seul utilisateur (0 - non, par défaut)

## définition des paramètres de la console de supervision des projets
$param['console_hour'] = "1";		// affichage de la supervision du temps (1 - oui, par défaut)
$param['console_salefigure'] = "1";		// affichage de la supervision du Chiffre d'Affaires (1 - oui, par défaut)
$param['console_cost'] = "1";		// affichage de la supervision des coûts (1 - oui, par défaut)
$param['console_project'] = "0";		// affichage de la supervision des détails d'un projet (0 - non, par défaut)
$param['console_finances'] = "0";		// affichage de la supervision des finances (0 - non, par défaut)

## définition des paramètres des contacts
$param['contact_access'] = "";		// niveau d'accès minimum pour les contacts ("" - tout le monde, par défaut)
$param['contact_format'] = "1";		// utilisation du formatage automatique des noms (1 - oui, par défaut)
$param['contact_user'] = "0";		// utilisation de la liaison d'un compte utilisateur sur un contact (0 - non, par défaut)
$param['contactoptions_textareas'] = "";	// liste des champs possibles -- avec du texte libre -- pour les contacts ("", par défaut)
$param['contactoptions_text'] = "";		// liste des champs possibles -- avec du texte libre -- pour les contacts ("", par défaut)
$param['contactoptions_textunique'] = ""; // liste des champs possibles -- avec du texte libre mais unique -- pour les customers ("", par défaut)
$param['contactoptions_date'] = "";		// liste des champs possibles -- avec une date -- pour les contacts ("", par défaut)
$param['contactoptions_user'] = "";		// liste des champs possibles -- avec un utilisateur -- pour les contacts ("", par défaut)
$param['contactoptions_selects'] = ""; // liste des champs possibles -- avec des select -- pour les contacts ("", par défaut)
$param['contactoptions_selectsmulti'] = ""; // liste des champs possibles -- avec des select -- pour les contacts ("", par défaut)

## définition des paramètres du calendrier
$param['calendar_picker'] = "1";		// affichage du picker pour le calendrier et l'horloge (1 - oui, par défaut)
$param['calendar-hour_middle'] = "13";		// heure de début de l'après-midi sur le calendrier (13 - 13h, par défaut)
$param['calendar-hour_start'] = "8";		// heure de début de journée sur le calendrier (8 - 8h, par défaut)
$param['calendar-hour_stop'] = "19";		// heure de fin de journée sur le calendrier (20 - 20h, par défaut)

## définition des paramètres de la gestion des notes de frais
$param['expenses_id'] = "0";		// affichage de l'id de chaque frais (0 - non, par défaut)
$param['expenses_billable'] = "0";		// affichage de l'option "facturable" sur chaque frais (0 - non, par défaut)
$param['expenses_prepaid'] = "0";		// affichage de l'option "pré-payé / CB" sur chaque frais (0 - non, par défaut)
$param['expenses_requestcheck'] = "1";		// case cochée devant les demandes de frais (1 - oui, par défaut)

## définition de la mise en page
$param['layout_type'] = "futura";		// affichage du tableau des données d'un projet (futura - futura, par défaut)
$param['layout_cssscreen'] = "styles_futura.css";		// fichier CSS pour la mise en plage à l'écran (styles_futura.css - futura, par défaut)
$param['layout_cssprint'] = "styles_print.css";		// fichier CSS pour la mise en plage à l'impression (styles_print.css - défaut, par défaut)
$param['layout_header'] = "";		// code HTML à afficher dans l'entête pour une navigation statique ("", par défaut)
$param['layout_footer'] = "";		// code HTML à afficher dans le pied de page pour une navigation statique ("", par défaut)
$param['layout_projectmenu'] = "doubleselect";		// type de menu pour afficher les niveaux supérieurs / inférieurs dans la navigation par onglets (doubleselect - double menu déroulant, par défaut)
$param['layout_jspacked'] = "1";		// utilisation d'une version compressée des fichiers JS (1 - oui, par défaut)
$param['layout_multiplestatus'] = "0";		// affichage de tous les messages d'information au lieu du dernier (0 - non)

## définition des paramètres de la gestion des courriels automatiques
$param['reminder_notice'] = "m";		// délai avant le déclenchement d'envoi d'email de rappel : m-mois, w-semaine ou d-jour (m - mois dernier, par défaut)

$param['email_auto'] = "1";		// envoie d'un courriel automatique pour les requêtes, les notes de frais, les demandes de congés (0 - non, par défaut)
$param['email_admin'] = "";		// adresse du responsable administratif ("", par défaut)
$param['email_external'] = "";		// adresse d'un contact externe ("", par défaut)
$param['email_from'] = "opentime@noparking.net";		// adresse de l'envoi des messages automatiques ("", par défaut)
$param['email_wrap'] = "50";		// nombre de caractères avant le retour à la ligne automatique (50 - 50 caractères, par défaut)
